// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc-mkadai.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	grpc-mkadai.proto

It has these top-level messages:
	Entry
	GetRequest
	GetResponse
	AddResponse
	PutRequest
	PutResponse
	DeleteRequest
	DeleteResponse
	RangeRequest
	WatchRequest
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Entry struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Entry) Reset()                    { *m = Entry{} }
func (m *Entry) String() string            { return proto1.CompactTextString(m) }
func (*Entry) ProtoMessage()               {}
func (*Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Entry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Entry) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type GetRequest struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetResponse struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type AddResponse struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *AddResponse) Reset()                    { *m = AddResponse{} }
func (m *AddResponse) String() string            { return proto1.CompactTextString(m) }
func (*AddResponse) ProtoMessage()               {}
func (*AddResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AddResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type PutRequest struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *PutRequest) Reset()                    { *m = PutRequest{} }
func (m *PutRequest) String() string            { return proto1.CompactTextString(m) }
func (*PutRequest) ProtoMessage()               {}
func (*PutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PutRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type PutResponse struct {
}

func (m *PutResponse) Reset()                    { *m = PutResponse{} }
func (m *PutResponse) String() string            { return proto1.CompactTextString(m) }
func (*PutResponse) ProtoMessage()               {}
func (*PutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type DeleteRequest struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto1.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DeleteRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto1.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type RangeRequest struct {
	StartKey string `protobuf:"bytes,1,opt,name=startKey" json:"startKey,omitempty"`
	MaxKeys  int32  `protobuf:"varint,2,opt,name=maxKeys" json:"maxKeys,omitempty"`
}

func (m *RangeRequest) Reset()                    { *m = RangeRequest{} }
func (m *RangeRequest) String() string            { return proto1.CompactTextString(m) }
func (*RangeRequest) ProtoMessage()               {}
func (*RangeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *RangeRequest) GetStartKey() string {
	if m != nil {
		return m.StartKey
	}
	return ""
}

func (m *RangeRequest) GetMaxKeys() int32 {
	if m != nil {
		return m.MaxKeys
	}
	return 0
}

type WatchRequest struct {
	Prefix string `protobuf:"bytes,1,opt,name=prefix" json:"prefix,omitempty"`
}

func (m *WatchRequest) Reset()                    { *m = WatchRequest{} }
func (m *WatchRequest) String() string            { return proto1.CompactTextString(m) }
func (*WatchRequest) ProtoMessage()               {}
func (*WatchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *WatchRequest) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func init() {
	proto1.RegisterType((*Entry)(nil), "proto.Entry")
	proto1.RegisterType((*GetRequest)(nil), "proto.GetRequest")
	proto1.RegisterType((*GetResponse)(nil), "proto.GetResponse")
	proto1.RegisterType((*AddResponse)(nil), "proto.AddResponse")
	proto1.RegisterType((*PutRequest)(nil), "proto.PutRequest")
	proto1.RegisterType((*PutResponse)(nil), "proto.PutResponse")
	proto1.RegisterType((*DeleteRequest)(nil), "proto.DeleteRequest")
	proto1.RegisterType((*DeleteResponse)(nil), "proto.DeleteResponse")
	proto1.RegisterType((*RangeRequest)(nil), "proto.RangeRequest")
	proto1.RegisterType((*WatchRequest)(nil), "proto.WatchRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Kvs service

type KvsClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Add(ctx context.Context, in *Entry, opts ...grpc.CallOption) (*AddResponse, error)
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	Range(ctx context.Context, in *RangeRequest, opts ...grpc.CallOption) (Kvs_RangeClient, error)
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (Kvs_WatchClient, error)
}

type kvsClient struct {
	cc *grpc.ClientConn
}

func NewKvsClient(cc *grpc.ClientConn) KvsClient {
	return &kvsClient{cc}
}

func (c *kvsClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := grpc.Invoke(ctx, "/proto.Kvs/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvsClient) Add(ctx context.Context, in *Entry, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := grpc.Invoke(ctx, "/proto.Kvs/Add", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvsClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	out := new(PutResponse)
	err := grpc.Invoke(ctx, "/proto.Kvs/Put", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvsClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := grpc.Invoke(ctx, "/proto.Kvs/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvsClient) Range(ctx context.Context, in *RangeRequest, opts ...grpc.CallOption) (Kvs_RangeClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Kvs_serviceDesc.Streams[0], c.cc, "/proto.Kvs/Range", opts...)
	if err != nil {
		return nil, err
	}
	x := &kvsRangeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Kvs_RangeClient interface {
	Recv() (*Entry, error)
	grpc.ClientStream
}

type kvsRangeClient struct {
	grpc.ClientStream
}

func (x *kvsRangeClient) Recv() (*Entry, error) {
	m := new(Entry)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *kvsClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (Kvs_WatchClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Kvs_serviceDesc.Streams[1], c.cc, "/proto.Kvs/Watch", opts...)
	if err != nil {
		return nil, err
	}
	x := &kvsWatchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Kvs_WatchClient interface {
	Recv() (*Entry, error)
	grpc.ClientStream
}

type kvsWatchClient struct {
	grpc.ClientStream
}

func (x *kvsWatchClient) Recv() (*Entry, error) {
	m := new(Entry)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Kvs service

type KvsServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Add(context.Context, *Entry) (*AddResponse, error)
	Put(context.Context, *PutRequest) (*PutResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	Range(*RangeRequest, Kvs_RangeServer) error
	Watch(*WatchRequest, Kvs_WatchServer) error
}

func RegisterKvsServer(s *grpc.Server, srv KvsServer) {
	s.RegisterService(&_Kvs_serviceDesc, srv)
}

func _Kvs_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Kvs/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvsServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kvs_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Entry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvsServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Kvs/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvsServer).Add(ctx, req.(*Entry))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kvs_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvsServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Kvs/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvsServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kvs_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Kvs/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvsServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kvs_Range_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RangeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KvsServer).Range(m, &kvsRangeServer{stream})
}

type Kvs_RangeServer interface {
	Send(*Entry) error
	grpc.ServerStream
}

type kvsRangeServer struct {
	grpc.ServerStream
}

func (x *kvsRangeServer) Send(m *Entry) error {
	return x.ServerStream.SendMsg(m)
}

func _Kvs_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KvsServer).Watch(m, &kvsWatchServer{stream})
}

type Kvs_WatchServer interface {
	Send(*Entry) error
	grpc.ServerStream
}

type kvsWatchServer struct {
	grpc.ServerStream
}

func (x *kvsWatchServer) Send(m *Entry) error {
	return x.ServerStream.SendMsg(m)
}

var _Kvs_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Kvs",
	HandlerType: (*KvsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Kvs_Get_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _Kvs_Add_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _Kvs_Put_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Kvs_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Range",
			Handler:       _Kvs_Range_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Watch",
			Handler:       _Kvs_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grpc-mkadai.proto",
}

func init() { proto1.RegisterFile("grpc-mkadai.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4d, 0x4f, 0xf2, 0x40,
	0x14, 0x85, 0x5b, 0x9a, 0xf2, 0xbe, 0x5e, 0xc0, 0xc0, 0x15, 0x0d, 0xe9, 0xc2, 0x8f, 0x31, 0x31,
	0xba, 0x10, 0x8d, 0x9a, 0xb8, 0x26, 0xc1, 0xb0, 0x60, 0x43, 0xba, 0x71, 0x3d, 0xd2, 0x2b, 0x12,
	0xbe, 0x6a, 0x67, 0x4a, 0xe0, 0x27, 0xf9, 0x2f, 0x0d, 0xd3, 0x61, 0x3a, 0xd8, 0x74, 0xd5, 0xde,
	0x3b, 0xe7, 0x9c, 0x39, 0x79, 0x06, 0x5a, 0x93, 0x24, 0x1e, 0xdf, 0x2f, 0x66, 0x3c, 0xe2, 0xd3,
	0x6e, 0x9c, 0xac, 0xe4, 0x0a, 0x7d, 0xf5, 0x61, 0x0f, 0xe0, 0xbf, 0x2d, 0x65, 0xb2, 0xc5, 0x26,
	0x78, 0x33, 0xda, 0x76, 0xdc, 0x4b, 0xf7, 0xf6, 0x28, 0xdc, 0xfd, 0x62, 0x1b, 0xfc, 0x35, 0x9f,
	0xa7, 0xd4, 0xa9, 0xa8, 0x5d, 0x36, 0xb0, 0x73, 0x80, 0x01, 0xc9, 0x90, 0xbe, 0x53, 0x12, 0xb2,
	0xe8, 0x62, 0xd7, 0x50, 0x53, 0xe7, 0x22, 0x5e, 0x2d, 0x05, 0xe5, 0x21, 0xae, 0x1d, 0x72, 0x01,
	0xb5, 0x5e, 0x14, 0x19, 0x51, 0x31, 0xe5, 0x05, 0x60, 0x94, 0x96, 0xdf, 0x52, 0xd2, 0xad, 0x01,
	0x35, 0xe5, 0xca, 0x62, 0xd9, 0x15, 0x34, 0xfa, 0x34, 0x27, 0x49, 0xe5, 0x6d, 0x9b, 0x70, 0xbc,
	0x97, 0x68, 0x53, 0x1f, 0xea, 0x21, 0x5f, 0x4e, 0x8c, 0x27, 0x80, 0xff, 0x42, 0xf2, 0x44, 0x0e,
	0x8d, 0xd1, 0xcc, 0xd8, 0x81, 0x7f, 0x0b, 0xbe, 0x19, 0xd2, 0x56, 0xa8, 0x1e, 0x7e, 0xb8, 0x1f,
	0xd9, 0x0d, 0xd4, 0xdf, 0xb9, 0x1c, 0x7f, 0xed, 0x53, 0xce, 0xa0, 0x1a, 0x27, 0xf4, 0x39, 0xdd,
	0xe8, 0x0c, 0x3d, 0x3d, 0xfd, 0x54, 0xc0, 0x1b, 0xae, 0x05, 0x76, 0xc1, 0x1b, 0x90, 0xc4, 0x56,
	0xf6, 0x38, 0xdd, 0x9c, 0x70, 0x80, 0xf6, 0x4a, 0x77, 0x74, 0xf0, 0x0e, 0xbc, 0x5e, 0x14, 0x61,
	0x5d, 0x1f, 0xaa, 0x27, 0x34, 0x52, 0x0b, 0x2d, 0x73, 0x76, 0xd1, 0xa3, 0x34, 0x8f, 0xce, 0xb1,
	0x1a, 0xbd, 0xcd, 0xcc, 0xc1, 0x57, 0xa8, 0x66, 0x48, 0xb0, 0xad, 0xcf, 0x0f, 0x20, 0x06, 0xa7,
	0x7f, 0xb6, 0xd6, 0x45, 0xbe, 0x22, 0x87, 0x27, 0x5a, 0x61, 0x73, 0x0c, 0x0e, 0xaa, 0x32, 0xe7,
	0xd1, 0xdd, 0xe9, 0x15, 0x23, 0xa3, 0xb7, 0x89, 0x15, 0xf5, 0x1f, 0x55, 0xb5, 0x78, 0xfe, 0x0d,
	0x00, 0x00, 0xff, 0xff, 0x94, 0x94, 0x20, 0x74, 0xcd, 0x02, 0x00, 0x00,
}
